### NUMPY Questions

In [1]:
import numpy as np

#### Create a 1D Numpy Array: Create a Numpy array containing numbers from 1 to 10.

In [2]:
array_1d = np.arange(1,11)

In [3]:
array_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Create a 2D Numpy Array: Create a 2D Numpy array with shape (3, 4) filled with random integers.

In [4]:
array_2d = np.random.randint(1, 50, size=(3, 4))

In [5]:
array_2d

array([[36, 44,  3, 38],
       [32, 19, 33, 25],
       [38, 47, 18, 48]])

#### Array Slicing: Perform slicing on a Numpy array to extract elements from index 2 to index 5.


In [6]:
sliced_array = array_2d[2:6]

In [7]:
sliced_array

array([[38, 47, 18, 48]])

#### Array Operations: Create two Numpy arrays of the same shape and perform element-wise addition.


In [9]:
arr_3d = np.random.randint(1,50,size=(2,3))

In [11]:
arr_4d = np.random.randint(1,50,size=(2,3))

## Pandas Questions:

#### Create a Pandas Series: Create a Pandas Series from a list of 5 colors.


In [1]:
import pandas as pd

In [5]:
data = ['red','green','blue','black','white']

In [7]:
df = pd.Series(data)

In [8]:
df

0      red
1    green
2     blue
3    black
4    white
dtype: object

#### Create a Pandas DataFrame: Create a Pandas DataFrame from a dictionary with columns 'Name', 'Age', and 'City' containing 5 rows of data.

In [10]:
# d = {'col1': [1, 2], 'col2': [3, 4]}
# df = pd.DataFrame(data=d)
details = {'Name':['ABBEY','BOB','CHANG','DANIAL','EVAN'], 'Age':[21,34,56,32,57], 'City':['New York','Paris','New Jersey','Amsterdam','Berlin']}

In [12]:
df = pd.DataFrame(data=details)

In [13]:
df

Name  Age        City
0   ABBEY   21    New York
1     BOB   34       Paris
2   CHANG   56  New Jersey
3  DANIAL   32   Amsterdam
4    EVAN   57      Berlin

#### DataFrame Operations: Perform basic operations on the DataFrame like head(), tail(), describe(), and info().

In [17]:
df.head(2)

Name  Age      City
0  ABBEY   21  New York
1    BOB   34     Paris

In [16]:
df.tail(2)

Name  Age       City
3  DANIAL   32  Amsterdam
4    EVAN   57     Berlin

In [19]:
df.describe()

Age
count   5.000000
mean   40.000000
std    15.858752
min    21.000000
25%    32.000000
50%    34.000000
75%    56.000000
max    57.000000

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    5 non-null      object
 1   Age     5 non-null      int64 
 2   City    5 non-null      object
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes


#### Filtering Data: Filter rows based on a specific condition, such as filtering rows where Age is greater than 30.

In [25]:
filtered_age = df[df['Age']> 30]

In [26]:
filtered_age

Name  Age        City
1     BOB   34       Paris
2   CHANG   56  New Jersey
3  DANIAL   32   Amsterdam
4    EVAN   57      Berlin